services:
  frontend:
    build: ./Frontend
    container_name: campusbike-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    env_file: ".env"
    depends_on:
      - springboot
  springboot:
    image: local/springboot_app
    container_name: springboot_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    env_file: ".env"
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file: ".env"
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -w ${POSTGRES_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Mount the schema file
  postgrest:
    image: postgrest/postgrest
    container_name: database_api
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGRST_DB_ANON_ROLE: ${POSTGRES_USER}
      # PGRST_JWT_SECRET: TODO: add this when we implement authentication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"] #TODO move to env
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres_data:
