services:
  frontend:
    build: ./Frontend
    container_name: campusbike-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_APP_ENV=dev
    depends_on:
      - springboot
  springboot:
    image: openjdk:21-jdk-slim
    container_name: springboot_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend # Set the working directory
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
    ports:
      - "8080:8080" # Expose the port your Spring Boot app runs on
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # This defines the named volume

