services:
  frontend:
    image: local/campusbike_frontend
    container_name: campusbike_frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_APP_ENV=dev
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - springboot
    # command: npm run dev 
  springboot:
    image: local/springboot_app
    container_name: springboot_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    env_file: ".env"
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file: ".env"
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -w ${POSTGRES_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Mount the schema file

volumes:
  postgres_data:
